# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ht8700_read_cpp <- function(filename) {
    .Call(`_gel_ht8700_read_cpp`, filename)
}

ht8700_read_cpp_gzip <- function(filename) {
    .Call(`_gel_ht8700_read_cpp_gzip`, filename)
}

match_times <- function(time1, time2, deltat) {
    .Call(`_gel_match_times`, time1, time2, deltat)
}

decal <- function(x, y) {
    .Call(`_gel_decal`, x, y)
}

licor_read_cpp <- function(filename) {
    .Call(`_gel_licor_read_cpp`, filename)
}

licor_read_cpp_gzip <- function(filename) {
    .Call(`_gel_licor_read_cpp_gzip`, filename)
}

hs_read_cpp <- function(filename) {
    .Call(`_gel_hs_read_cpp`, filename)
}

hs_read_cpp_gzip <- function(filename) {
    .Call(`_gel_hs_read_cpp_gzip`, filename)
}

