# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hs_read_cpp <- function(filename) {
    .Call(`_gel_hs_read_cpp`, filename)
}

hs_read_cpp_gzip <- function(filename) {
    .Call(`_gel_hs_read_cpp_gzip`, filename)
}

